export const COST_LIST = [
  { category: "행위료", name: "2인실", price: "250,000" },
  { category: "행위료", name: "수체질(2주)", price: "385,000" },
  { category: "행위료", name: "목체질(2주)", price: "440,000" },
  { category: "행위료", name: "금체질(2주)", price: "495,000" },
  { category: "행위료", name: "토체질(2주)", price: "330,000" },
  { category: "행위료", name: "녹용(2주)", price: "550,000" },
  { category: "행위료", name: "슬림정", price: "180,000" },
  { category: "행위료", name: "슬림환 (1포)", price: "2,000" },
  { category: "행위료", name: "상비한약(1일/2팩)", price: "10,000" },
  { category: "행위료", name: "소화환", price: "9,000" },
  { category: "행위료", name: "경옥고", price: "150,000" },
  { category: "행위료", name: "디톡스환(7일/14포)", price: "35,000" },
  { category: "행위료", name: "숙취해소환(2포)", price: "5,000" },
  { category: "행위료", name: "원방공진단", price: "50,000" },
  { category: "행위료", name: "사향공진단", price: "35,000" },
  { category: "행위료", name: "침향공진단", price: "15,000" },
  { category: "행위료", name: "봉약침(1회)", price: "29,000" },
  { category: "행위료", name: "자하거(1회)", price: "29,000" },
  { category: "행위료", name: "어혈약침(1회)", price: "29,000" },
  { category: "행위료", name: "지방분해약침(1회)", price: "50,000" },
  { category: "행위료", name: "프리미엄약침(1회)", price: "100,000" },
  { category: "행위료", name: "통증매선(1회)", price: "70,000" },
  { category: "행위료", name: "안면매선(1회)", price: "300,000" },
  { category: "행위료", name: "비급여 추나-복잡", price: "21,800" },
  { category: "치료재료대", name: "한방파스", price: "6,000" },
  { category: "치료재료대", name: "시프겔", price: "10,000" },
  { category: "치료재료대", name: "자운고", price: "6,000" },
  { category: "제증명수수료", name: "진단서(일반)", price: "20,000" },
  { category: "제증명수수료", name: "진단서(근로능력평가용)", price: "20,000" },
  { category: "제증명수수료", name: "영문진단서", price: "20,000" },
  { category: "제증명수수료", name: "소견서", price: "20,000" },
  { category: "제증명수수료", name: "확인서(통원)", price: "3,000" },
  { category: "제증명수수료", name: "확인서(진료)", price: "3,000" },
  { category: "제증명수수료", name: "입원사실증명서", price: "3,000" },
  { category: "제증명수수료", name: "진료기록사본(1-5매)", price: "장당 1,000" },
  { category: "제증명수수료", name: "진료기록사본(6매)", price: "장당 100" },
  { category: "제증명수수료", name: "영수증", price: "-" },
  { category: "제증명수수료", name: "세부산정내역서", price: "-" },
  { category: "제증명수수료", name: "요양(급여)의뢰서", price: "-" }
];